import { describe, expect, it } from "vitest";
import { createProjectFromBrief } from "./pipeline";
import { validateReferenceCardProject } from "./card-template-quality";
import type { Brief } from "../types";

const brief: Brief = {
	id: "brief-quality",
	title: "월급이 매달 사라지는 이유",
	topic: "월급이 매달 사라지는 이유",
	intent: "info",
	tone: "serious",
	targetDuration: 30,
	platform: "youtube",
	language: "ko",
	audience: "직장인",
	thesis: "돈이 모이지 않는 이유는 소비 순서가 고정되어 있지 않기 때문입니다.",
};

describe("reference card quality gate", () => {
	it("passes projects generated by the pipeline", () => {
		const project = createProjectFromBrief(
			brief,
			[
				"월급이 매달 사라지는 이유, 문제는 의지가 아니라 돈이 빠지는 순서입니다.",
				"월급날 남은 돈을 저축하려고 하면 저축은 항상 마지막 순서로 밀립니다.",
				"고정비를 먼저 분리하지 않으면 생활비가 계획보다 빨리 무너집니다.",
				"돈이 모이는 사람은 월급날 빠질 돈부터 먼저 잠급니다.",
				"오늘 저축, 고정비, 생활비 계좌를 먼저 나눠보세요.",
			].join("\n"),
		);

		const report = validateReferenceCardProject(project);
		expect(report.ok).toBe(true);
		expect(report.score).toBe(100);
	});

	it("flags layout or text overflow regressions", () => {
		const project = createProjectFromBrief(brief, brief.thesis);
		const broken = {
			...project,
			scenes: project.scenes.map((scene, index) =>
				index === 0
					? {
							...scene,
							layout: "split",
							text: "너무 긴 문장이 계속 이어져서 카드형 쇼츠 중앙 헤드라인 영역을 넘어가고 하단 자막칩과 진행바까지 침범할 가능성이 큰 상태입니다.".repeat(2),
						}
					: scene,
			),
		};

		const report = validateReferenceCardProject(broken);
		expect(report.ok).toBe(false);
		expect(report.issues.join(" ")).toContain("레이아웃");
		expect(report.issues.join(" ")).toContain("안전 영역");
	});

	it("flags duplicate numbering that would fight the fixed card labels", () => {
		const project = createProjectFromBrief(brief, brief.thesis);
		const broken = {
			...project,
			scenes: project.scenes.map((scene, index) =>
				index === 1 ? { ...scene, text: "첫째, 고정비를 먼저 분리합니다." } : scene,
			),
		};

		const report = validateReferenceCardProject(broken);
		expect(report.ok).toBe(false);
		expect(report.issues.join(" ")).toContain("라벨");
	});
});
