/**
 * Subtitle format generators (WebVTT / ASS) — augmenting the SRT path in render-package.ts.
 *
 * - WebVTT (`.vtt`): used by HTML5 <track>, YouTube/web players.
 * - ASS / SubStation Alpha (`.ass`): supports rich styling, used by Aegisub and FFmpeg subtitles filter.
 */
import type { ShortsProject } from "../types";

export interface SubtitleCue {
	index: number;
	start: number;
	end: number;
	lines: string[];
}

/** Project → ordered cues with absolute timestamps. */
export function projectToCues(project: ShortsProject): SubtitleCue[] {
	let elapsed = 0;
	return project.scenes.map((scene, index) => {
		const start = elapsed;
		elapsed += scene.duration;
		return {
			index: index + 1,
			start,
			end: elapsed,
			lines: scene.subtitles.lines,
		};
	});
}

export function buildVtt(project: ShortsProject): string {
	const header = "WEBVTT\n\n";
	const body = projectToCues(project)
		.map((cue) => {
			const start = formatVttTimestamp(cue.start);
			const end = formatVttTimestamp(cue.end);
			return [`cue-${cue.index}`, `${start} --> ${end}`, cue.lines.join("\n")].join(
				"\n",
			);
		})
		.join("\n\n");
	return header + body + "\n";
}

export function buildAss(project: ShortsProject): string {
	const lines = [
		"[Script Info]",
		"; Generated by Card Short Maker",
		"ScriptType: v4.00+",
		"PlayResX: 1080",
		"PlayResY: 1920",
		"WrapStyle: 0",
		"ScaledBorderAndShadow: yes",
		"",
		"[V4+ Styles]",
		"Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
		"Style: Default,Pretendard,72,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,1,0,0,0,100,100,2,0,1,4,2,2,40,40,180,1",
		"",
		"[Events]",
		"Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
	];

	for (const cue of projectToCues(project)) {
		const start = formatAssTimestamp(cue.start);
		const end = formatAssTimestamp(cue.end);
		const text = cue.lines.join("\\N");
		lines.push(`Dialogue: 0,${start},${end},Default,,0,0,0,,${text}`);
	}

	return lines.join("\n") + "\n";
}

function formatVttTimestamp(seconds: number): string {
	const ms = Math.max(0, Math.round(seconds * 1000));
	const h = Math.floor(ms / 3_600_000);
	const m = Math.floor((ms % 3_600_000) / 60_000);
	const s = Math.floor((ms % 60_000) / 1000);
	const milli = ms % 1000;
	return `${pad(h)}:${pad(m)}:${pad(s)}.${String(milli).padStart(3, "0")}`;
}

function formatAssTimestamp(seconds: number): string {
	const totalMs = Math.max(0, Math.round(seconds * 1000));
	const h = Math.floor(totalMs / 3_600_000);
	const m = Math.floor((totalMs % 3_600_000) / 60_000);
	const s = Math.floor((totalMs % 60_000) / 1000);
	const cs = Math.floor((totalMs % 1000) / 10);
	return `${h}:${pad(m)}:${pad(s)}.${pad(cs)}`;
}

function pad(value: number): string {
	return String(value).padStart(2, "0");
}
